env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-ignore: allow-with-description
      ts-expect-error: allow-with-description
      ts-nocheck: true
      ts-check: false
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  max-len:
    - error
    - code: 150