openapi: 3.0.3
info:
  title: Proof Market V2
  description: Proof Market V2
  version: 1.0.0
servers:
  - url: 'https://localhost:3000'
paths:
  /user/signup:
    post:
      summary: User signup
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                passwd:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: number
                  jwt:
                    type: string

  /user/signin:
    post:
      summary: User signin
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: number
                  jwt:
                    type: string
        '401':
          description: Invalid credentials

  /user/balance:
    get:
      summary: Get user balance
      operationId: balance
      responses:
        '200':
          description: Balance retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: string
                  balance:
                    type: number
                  blocked:
                    type: number
        '401':
          description: Unauthorized
        '400':
          description: User not found

  /user/exists/{id}:
    head:
      summary: Check if user exists
      operationId: exists
      parameters:
        - in: path
          name: login
          required: true
          schema:
            type: string
          description: Login
      responses:
        '200':
          description: User exists
        '404':
          description: User not found
