version: '3.8'

services:
  db:
    container_name: proof_market_db
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-proof_market}
      POSTGRES_USER: ${POSTGRES_USER:-proof_market}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-proof_market_pass}
    ports:
      - "15433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
